# Import libraries 

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import string
import re
import codecs
import seaborn as sns
from sklearn import feature_extraction, linear_model,pipeline
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [3]:
#loading data 
lan_data = pd.read_csv("D:/harshita/project/language detection/Language Detection.csv")
lan_data.head(4)

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English

In [4]:
lan_data.get('Text')

0         Nature, in the broadest sense, is the natural...
1        "Nature" can refer to the phenomena of the phy...
2        The study of nature is a large, if not the onl...
3        Although humans are part of nature, human acti...
4        [1] The word nature is borrowed from the Old F...
                               ...                        
10332    ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...
10333    ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...
10334    ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...
10335    ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...
10336    ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...
Name: Text, Length: 10337, dtype: object

In [5]:
#changing text column data into lowercase

lan_data['Text']= lan_data['Text'].str.lower()
lan_data

Text Language
0       nature, in the broadest sense, is the natural...  English
1      "nature" can refer to the phenomena of the phy...  English
2      the study of nature is a large, if not the onl...  English
3      although humans are part of nature, human acti...  English
4      [1] the word nature is borrowed from the old f...  English
...                                                  ...      ...
10332  ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...  Kannada
10333  ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...  Kannada
10334  ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...  Kannada
10335  ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...  Kannada
10336  ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...  Kannada

[10337 rows x 2 columns]

# data cleaning

In [ ]:
# remove special characters
lan_data['Text']= lan_data['Text'].str.replace('\W', ' ', regex= True)
lan_data.head(100)

In [8]:
#removing numaric value using function
def chn_digit(con):
    con = re.sub(r'\d+',' ',con)
    return con


In [9]:
#applying changes on dataset
lan_data['Text']=lan_data['Text'].apply(chn_digit)
lan_data

Text Language
0       nature  in the broadest sense  is the natural...  English
1       nature  can refer to the phenomena of the phy...  English
2      the study of nature is a large  if not the onl...  English
3      although humans are part of nature  human acti...  English
4          the word nature is borrowed from the old f...  English
...                                                  ...      ...
10332  ನ ಮ ಮ ತಪ ಪ  ಏನ  ಬ ದ ದ ಯ  ದರ  ಆ ದ ನದ  ದ ನ ಮಗ  ಒ...  Kannada
10333  ನ ರ ಸ ಸ  ತ ನ  ಮ ದಲ ಗ  ಹ ಣಗ ಡ ತ ತ ದ ದ ಮ ರ ಗಗಳನ ...  Kannada
10334  ಹ ಗ    ನ ರ ಸ ಸ ಸಮ  ಈಗ ಮರ ಯನ  ಅವರ ಗ  ಸ ಭವ ಸ ದ ಎ...  Kannada
10335  ಅವಳ  ಈಗ ಹ ಚ ಚ  ಚ ನ ನದ ಬ ರ ಡ  ಬಯಸ ವ ದ ಲ ಲ ಎ ದ  ...  Kannada
10336  ಟ ರ ರ  ನ ವ  ನ ಜವ ಗ ಯ  ಆ ದ ವದ ತನ ತ  ಸ ವಲ ಪ ಕ ಣ ...  Kannada

[10337 rows x 2 columns]

# model preparation

In [15]:
#spliting data into train ans test 
x,y = lan_data.iloc[:,0], lan_data.iloc[:,1]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state =0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)



(8269,)
(2068,)
(8269,)
(2068,)


Vectorization and  pipeline for Model Fitting

In [19]:

vect = feature_extraction.text.TfidfVectorizer(ngram_range=(1,3),analyzer='char')
pipe_33= pipeline.Pipeline([('vectorizer',vect),
                            ('clf',linear_model.LogisticRegression())])


In [20]:
#model Training
pipe_33.fit(x_train ,y_train)

Pipeline(steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char', ngram_range=(1, 3))),
                ('clf', LogisticRegression())])

In [23]:
#model_prediction
y_predi = pipe_33.predict(x_test)


In [24]:
#model_evalution
acc = (metrics.accuracy_score(y_test,y_predi))*100
print(acc,'%')

98.11411992263056 %


In [26]:
matrix = metrics.confusion_matrix(y_test,y_predi)
print(matrix)

[[116   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0]
 [  0  72   0   1   0   0   0   0   0   0   0   0   0   1   3   0   0]
 [  0   1 103   2   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   1 256   1   0   0   0   1   0   0   0   0   1   0   0   0]
 [  0   0   0   1 193   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0   3   0   0 102   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  70   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 146   0   0   4   0   2   0   0   0]
 [  0   0   0   0   0   0   0   0   0  77   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 114   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0 147   0   2   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0 142   0   0   0   0]
 [  0   0   1   0   0   0   0   0   2   0   1   2   0 151   1   0   0]
 [  0 

ValueError: Image size of 400000x600000 pixels is too large. It must be less than 2^16 in each direction.

ValueError: Image size of 400000x600000 pixels is too large. It must be less than 2^16 in each direction.

<Figure size 400000x600000 with 2 Axes>

# Saving Model for Future use

In [35]:
#model saving
import pickle
irFile = open('LRModel.pckl','wb')
pickle.dump(pipe_33,irFile)
irFile.close()

In [37]:
#model_loading
global lrLangDetectModel
lrLangDetectFile = open('LRmodel.pckl','rb')
lrLangDetectModel = pickle.load(lrLangDetectFile)
lrLangDetectFile.close()

# Final Model 

In [40]:
#model
def lang_detect(text):
    import numpy as np
    import string
    import re
    import pickle
    
    translate_table = dict((ord(char),None)for char in string.punctuation)
    
    global lrLangDetectModel
    lrLangDetectFile = open('LRModel.pckl','rb')
    lr_model = pickle.load(lrLangDetectFile)
    lrLangDetectFile.close()
    
    
    text = ' '.join(text.split())
    text = text.lower()
    text = re.sub(r'\d+',' ',text)
    text = text.translate(translate_table)
    pred = lrLangDetectModel.predict([text])
    prob =lrLangDetectModel.predict_proba([text])
    return pred[0]
   
    

# final outcome

In [49]:
text = ['my name is harshita','mi nombre es shurita','il mio nome è hardita',
   'ನನ್ನ ಹೆಸರು ಹರ್ಷಿತಾ'   ]





In [50]:
for i in text:
    print(lang_detect(i))

English
Spanish
Italian
Kannada


# Thank-You 